id: P0DF9C80B
initial_creation_type: input
source_metadata:
  title: 'Nāgārjuna: Mūlamadhyamakakārikā'
  language: zh
  volumes:
    89d15d731134493197eb5a7e0b24d9e7:
      title: 'CIII_Chapter XI: Pūrvāparakoṭiparīkṣa'
      base_file: 'CIII_Chapter XI: Pūrvāparakoṭiparīkṣa.txt'
      work_id: W393D88E5
    bfa51880a22f420e9d44ab3b68308e5b:
      title: 'CIII_Chapter XII: Duḥkhaparīkṣā'
      base_file: 'CIII_Chapter XII: Duḥkhaparīkṣā.txt'
      work_id: W77AB1228
    2ee6532f8ec642bd9650b34ba2055927:
      title: 'CIII_Chapter XIII: Saṃskāraparīkṣā'
      base_file: 'CIII_Chapter XIII: Saṃskāraparīkṣā.txt'
      work_id: W61BF6F43
    a16331e84dcb4763974b9ceb82a48a6b:
      title: 'CIII_Chapter XIV: Saṃsargaparīkṣā'
      base_file: 'CIII_Chapter XIV: Saṃsargaparīkṣā.txt'
      work_id: W4C4C54FF
    24f6550f34b84874831fecf5b7f6cc07:
      title: 'CIII_Chapter XV: Svabhāvaparīkṣā'
      base_file: 'CIII_Chapter XV: Svabhāvaparīkṣā.txt'
      work_id: W3955F31D
    eab37b80525b46e6a1631d19c593d2b0:
      title: 'CII_Chapter IX: Pūrvaparīkṣā'
      base_file: 'CII_Chapter IX: Pūrvaparīkṣā.txt'
      work_id: WCE2BB12E
    de4c4c318d6b40adb12ad092dca5d9a2:
      title: 'CII_Chapter VI: Rāgasaktiparīkṣā'
      base_file: 'CII_Chapter VI: Rāgasaktiparīkṣā.txt'
      work_id: W709C3460
    e196c85d618643e3b38913418cf49455:
      title: 'CII_Chapter VII: Saṃskr̥̥taparīkṣā'
      base_file: 'CII_Chapter VII: Saṃskr̥̥taparīkṣā.txt'
      work_id: WED83278C
    4fded6d6832a41c4afb3de344c2331a8:
      title: 'CII_Chapter VIII: Karmakārakaparīkṣā'
      base_file: 'CII_Chapter VIII: Karmakārakaparīkṣā.txt'
      work_id: W6371DE83
    a96e48c97a9e4bf88077e7532a28dd5e:
      title: 'CII_Chapter X: Agnīndhanaparīkṣā'
      base_file: 'CII_Chapter X: Agnīndhanaparīkṣā.txt'
      work_id: WF74CD273
    975998a0add74d26963c02883f6e3ae0:
      title: 'CIV_Chapter XIX: Kālaparīkṣā'
      base_file: 'CIV_Chapter XIX: Kālaparīkṣā.txt'
      work_id: W3F09DA5F
    c170f9a5bcc543cf925a28bcbfd034eb:
      title: 'CIV_Chapter XVI: Bandhanamokṣaparīkṣā'
      base_file: 'CIV_Chapter XVI: Bandhanamokṣaparīkṣā.txt'
      work_id: W6BF44586
    97c649e7e9e847cba4f4365b3dad3f51:
      title: 'CIV_Chapter XVII: Karmaphalaparīkṣā'
      base_file: 'CIV_Chapter XVII: Karmaphalaparīkṣā.txt'
      work_id: W281E98EE
    1f5995ad85174c7399db13f047b25710:
      title: 'CIV_Chapter XVIII: Ātmaparīkṣā'
      base_file: 'CIV_Chapter XVIII: Ātmaparīkṣā.txt'
      work_id: W8E7771AA
    38a596f3e5bb4903bac167a4b1cb0c97:
      title: 'CIV_Chapter XX: Sāmagrīparīkṣā'
      base_file: 'CIV_Chapter XX: Sāmagrīparīkṣā.txt'
      work_id: WD2404C54
    85db162ddf354aff99ce4a4ecd539af2:
      title: 'CI_Chapter I: Pratyayaparīkṣā'
      base_file: 'CI_Chapter I: Pratyayaparīkṣā.txt'
      work_id: WCFB97757
    4678d3fe5dbf43188243c9914fcc745d:
      title: 'CI_Chapter II: Gatāgataparīkṣaṇa'
      base_file: 'CI_Chapter II: Gatāgataparīkṣaṇa.txt'
      work_id: W8A423FD5
    9990b1c6714a4af785075ec004b9b858:
      title: 'CI_Chapter III: Cakṣurādīndriyaparīkṣā'
      base_file: 'CI_Chapter III: Cakṣurādīndriyaparīkṣā.txt'
      work_id: W2C7B95E3
    3451ca6f7d2d4ae491f9f130b1d982cf:
      title: 'CI_Chapter IV: Skandhaparīkṣā'
      base_file: 'CI_Chapter IV: Skandhaparīkṣā.txt'
      work_id: WA986AB39
    790829838f014b97813a24e34186a3a0:
      title: 'CI_Chapter V: Dhātuparīkṣā'
      base_file: 'CI_Chapter V: Dhātuparīkṣā.txt'
      work_id: WE9CECCB0
    51c8deb73cbf46bebd825d3a98cad8ce:
      title: 'CVI_Chapter XXVI: Dvādaśāṅgaparīkṣā'
      base_file: 'CVI_Chapter XXVI: Dvādaśāṅgaparīkṣā.txt'
      work_id: WED8D2353
    c1dcbcf3006547979729652af1713b05:
      title: 'CVI_Chapter XXVII: Dr̥ṣṭiparīkṣā'
      base_file: 'CVI_Chapter XXVII: Dr̥ṣṭiparīkṣā.txt'
      work_id: W02143A41
    6e8d620f9cee4a36b894c64bf6400f67:
      title: 'CV_Chapter XXI: Saṃbhavavibhavaparīkṣā'
      base_file: 'CV_Chapter XXI: Saṃbhavavibhavaparīkṣā.txt'
      work_id: WC691F774
    2661dc456f7f4aa599e4802f1cef4da1:
      title: 'CV_Chapter XXII: Tathāgataparīkṣā'
      base_file: 'CV_Chapter XXII: Tathāgataparīkṣā.txt'
      work_id: W12C37BC8
    a985d09005c94a85a5a0cf81288caa32:
      title: 'CV_Chapter XXIII: Viparyāsaparīkṣā'
      base_file: 'CV_Chapter XXIII: Viparyāsaparīkṣā.txt'
      work_id: W9E9E777F
    da03b186026c44f29ac3325e2f6d7641:
      title: 'CV_Chapter XXIV: Āryasatyaparīkṣā'
      base_file: 'CV_Chapter XXIV: Āryasatyaparīkṣā.txt'
      work_id: W48DB44E0
    cdabc6f7a0b944599476bb352351105b:
      title: 'CV_Chapter XXV: nirvāṇaparīkṣā'
      base_file: 'CV_Chapter XXV: nirvāṇaparīkṣā.txt'
      work_id: W7CC89619
    d153a37d7a6a4f5aab39ca9c885e1daa:
      title: Colophon
      base_file: Colophon.txt
      work_id: W175C6BD6
    71b44c91c8a949f3a1a0f0eceb79d3db:
      title: Preface
      base_file: Preface.txt
      work_id: WE029D37D
    a364b92b4670412d8fb208af2a75f482:
      title: Title
      base_file: Title.txt
      work_id: W451AACED
  chapter_to_tile:
    CI: Chapters I-V
    CII: Chapters VI-X
    CIII: Chapters XI-XV
    CIV: Chapters XVI-XX
    CV: Chapters XXI-XXV
    CVI: Chapters XXVI-XXVII
created_at: '2022-03-01T23:08:55.761660'
last_modified_at: '2022-03-01T23:08:55.761667'
